import React from 'react';

import Layout from '../../components/Layout';
import Section from '../../components/section/Section';
import Card from '../../components/card/Card';

export const SpecialityToursTemplate = () => {
	// TODO: This is a critical page that needs to be generated by the CMS. It should be possible to dynamically generate pages like this entirely through the CMS
	return (
		<Section
			sectionClasses={['section', 'programs']}
			containerClasses={['container']}
		>
			{/* TODO: These cards need to come from the CMS */}
			<div class="columns is-multiline">
				<div class="column is-full fls__content-header">
					<div class="columns is-centered is-multiline">
						<div class="column is-full has-text-centered">
							{/* TODO: This title/subtitle/copy pattern can likely be componentized */}
							<h3 class="subtitle subtitle--fls subtitle--red">
								Programs
							</h3>
							<h2 class="title title--fls">Speciality Tours</h2>
						</div>
						<div class="column is-full">
							<p class="fls__content-header-copy has-text-centered">
								Explore your favorite subject or sport, or just
								enjoy the sights, as you study at the most
								fascinating destinations in the United States!
							</p>
						</div>
					</div>
				</div>

				<div class="column is-one-third-desktop is-half-tablet">
					<Card isSpecialityTours={true} />
				</div>
			</div>
		</Section>
	);
};

const SpecialityToursPage = ({ data }) => {
	// const { frontmatter } = data.markdownRemark;

	console.log('data from query', data);
	return (
		<Layout isScrolled={true} hasNavHero={true} pageTitle={'Programs'}>
			<SpecialityToursTemplate />
		</Layout>
	);
};

export default SpecialityToursPage;

// TODO: Here, all the individual fields are specified.
// Is there a way to just say 'get all fields'?
// export const pageQuery = graphql`
// 	query {
// 		markdownRemark {
// 			frontmatter {
// 				program_cards {
// 					card_description
// 					card_image
// 					card_title
// 				}
// 			}
// 		}
// 	}
// `;
