import React, { Fragment } from 'react';

import Layout from 'src/components/Layout';
import Section from 'src/components/section/Section';
import HorizontalNav from 'src/components/horizontal-nav/HorizontalNav';
import Card from 'src/components/card/Card';

export const AboutUsTemplate = () => {
	// TODO: This is a critical page that needs to be generated by the CMS. It should be possible to dynamically generate pages like this entirely through the CMS
	return (
		<Fragment>
			<Section
				sectionClasses={['section']}
				containerClasses={['container']}
			>
				<div className="columns is-multiline">
					<HorizontalNav
						navItems={[
							'Welcome',
							'Mission Statement',
							'FLS Advantage',
							'Ethical Conduct',
							'Accreditations',
							'Our Team',
						]}
					/>

					<div className="column is-full">
						<div className="columns is-variable is-5">
							<div className="column is-3">
								<figure className="image is-4by5">
									{/* TODO: There is an annoying gap on the left side of this image, when rendered on the page */}
									<img src="../../img/francine-img.png" />
								</figure>
							</div>

							<div className="column is-9">
								<h1 className="title title--fls">
									Welcome to Fls
								</h1>

								<p className="fls__generic-copy">
									With globalization increasing, it’s more
									important than ever to learn about other
									cultures. There’s no better way to
									understand a new culture than by learning
									its language. This is what FLS International
									has been about for over 30 years.
								</p>

								<p className="fls__generic-copy">
									By joining an FLS program, students improve
									their English, gain an understanding of
									other cultures and develop their
									independence. Studying overseas can be
									life-changing, leading students to challenge
									themselves, find their true passions and
									increase their personal growth.
								</p>

								<p className="fls__generic-copy">
									At FLS we invite each student to appreciate
									the allure of a new language and immerse
									themselves in a new culture. We strive to
									give students both the edge and motivation
									necessary to become part of the global
									marketplace and pursue endless opportunities
									for personal growth.
								</p>

								<p className="fls__generic-copy">
									As America’s largest network of family-owned
									and operated language schools, FLS is proud
									of our excellent record of student
									satisfaction and client service. For over
									three decades, we have offered programs that
									entice students to reach new levels of
									success and expand their dreams. With our
									responsiveness and individualized attention
									to student concerns, we are confident that
									FLS is the best choice for a unique and
									valuable American experience.
								</p>

								<p className="fls__generic-copy">Sincerely,</p>

								<img
									className="about-us__contact-card-icon"
									src="../../img/francine-signature.png"
									alt="Francine Forman Swain signature"
								/>

								<p className="fls__generic-copy">
									Francine Forman Swain
								</p>

								<p>Director and Founder - FLS International</p>
							</div>
						</div>
					</div>
				</div>
			</Section>

			<Section
				sectionClasses={['section', 'highlighted-section']}
				containerClasses={['container']}
			>
				<div className="columns is-centered is-multiline">
					<div className="column is-full">
						<div className="section__title-container">
							<h2 className="title title--fls title--white title--underline">
								Mission Statement
							</h2>
						</div>
					</div>

					<div className="column is-9">
						<p className="highlighted-section__copy">
							FLS International is committed to providing
							effective English as a Foreign Language education
							and cultural training to international students and
							assisting clients during each phase of their
							educational experience, from their initial entry
							into the United States to their transfer to a
							college or university.
						</p>
					</div>
				</div>
			</Section>

			<Section
				sectionClasses={['section']}
				containerClasses={['container']}
			>
				<div className="columns is-centered is-multiline">
					<div className="column is-8 has-text-centered">
						<h3 className="subtitle subtitle--fls subtitle--red">
							The
						</h3>
						<h2 className="title title--fls">FLS Advantage</h2>
						<div className="section__title-copy">
							Here are just a few of the reasons why FLS
							International offers international students an
							unbeatable learning and cultural experience. As
							America’s largest family-owned and operated network
							of language schools, we pride ourselves on our
							personalized and flexible service.
						</div>
					</div>

					{/* TODO: we'll need to make sure any arbitrary amount of bullet points can be inputted, and that they will render (reasonably) well */}
					<div className="column is-half">
						{/* TODO: Figure out icons */}
						<ul>
							<li className="fls__list-item">
								Small class sizes ensuring individual student
								attention.
							</li>
							<li className="fls__list-item">
								College and university placement assistance at
								no additional charge.
							</li>
							<li className="fls__list-item">
								Programs using the immersion method of language
								instruction, emphasizing spoken English.
							</li>
							<li className="fls__list-item">
								Structured Pathway programs to effectively
								prepare students for college entrance.
							</li>
							<li className="fls__list-item">
								Eighteen levels of English study.
							</li>
							<li className="fls__list-item">
								Unique English Everywhere program highlighting
								key curriculum points each week.
							</li>
						</ul>
					</div>

					<div className="column is-half">
						{/* TODO: Figure out icons */}
						<ul>
							<li className="fls__list-item">
								Experienced academic counselors.
							</li>
							<li className="fls__list-item">
								Accreditation by CEA (Commission on English
								Language Program Accreditation).
							</li>
							<li className="fls__list-item">
								Centers located in secure, safe environments.
							</li>
							<li className="fls__list-item">
								Monthly Language Extension Day, letting students
								use their English in new settings.
							</li>
							<li className="fls__list-item">
								Highly qualified teaching staff with all faculty
								holding Master’s Degrees or TESOL credentials.
							</li>
						</ul>
					</div>
				</div>
			</Section>

			<Section
				sectionClasses={['section', 'section--alternate']}
				containerClasses={['container']}
			>
				<div className="columns is-centered is-multiline">
					<div className="column is-full has-text-centered">
						<h3 className="subtitle subtitle--fls subtitle--red">
							About
						</h3>
						<h2 className="title title--fls">Ethical Conduct</h2>
					</div>

					<div className="column is-full">
						<div className="columns">
							<div className="column is-9 fls__post-container">
								<h3 className="fls-post__title">Integrity</h3>

								<p className="fls__post-copy">
									We will manifest the highest level of
									integrity in all our professional
									undertakings, dealing with others honestly
									and fairly, abiding by our commitments, and
									always acting in a manner that merits the
									trust and confidence others have placed in
									us.
								</p>

								<h3 className="fls-post__title">
									Respect For The Law
								</h3>

								<p className="fls__post-copy">
									We will follow all applicable laws and
									regulations and carefully and reflectively
									advise students and scholars regarding those
									laws and regulations. We will seek out
									appropriate guidance and advice when
									regulations appear contradictory, ambiguous,
									or confusing or when a situation is beyond
									our role or competency.
								</p>

								<h3 className="fls-post__title">Quality</h3>

								<p className="fls__post-copy">
									We will strive constantly to provide high
									quality and educationally valuable programs
									and services. We regularly will evaluate and
									review our work in order to improve those
									programs and services and will seek out and
									adopt exemplary practices.
								</p>

								<h3 className="fls-post__title">Competence</h3>

								<p className="fls__post-copy">
									We will undertake our work with the highest
									levels of competence and professionalism,
									regularly seeking and acquiring the training
									and knowledge necessary to do so. Our
									commitment to professional competence will
									extend to exercising thorough oversight of
									external programs and placements. Through
									careful planning and the development and
									implementation of appropriate policies, we
									will do our utmost to ensure the safety,
									security, and success of students, staff,
									faculty, and scholars.
								</p>
							</div>

							<div className="column is-3">
								<img src="../../img/about-img-1.jpeg" alt="" />
							</div>
						</div>
					</div>

					<div className="column is-full">
						<div className="columns">
							<div className="column is-3">
								<img src="../../img/about-img-2.jpeg" alt="" />
							</div>

							<div className="column is-9 fls__post-container--left">
								<h3 className="fls-post__title">Diversity</h3>

								<p className="fls__post-copy">
									In both word and deed we will respect the
									dignity and worth of all people and be
									properly attentive and responsive to the
									beliefs and cultural commitments of others.
									In the planning, development, and
									implementation of programs and services we
									will engage respectfully with the diversity
									of peoples and perspectives. We will strive
									to ensure that our programs reflect the
									diversity of our institutions and their
									educational goals.
								</p>

								<h3 className="fls-post__title">
									Transparency
								</h3>

								<p className="fls__post-copy">
									We will demonstrate the appropriate level of
									transparency in dealings with individuals
									and organizations. In collaborations with
									other institutions and individuals we will
									proceed on the bases of equality and
									mutuality. Transactions with external
									providers of programs and services will be
									conducted professionally, always keeping the
									welfare of students foremost, and disclosing
									any potential conflicts of interests. We
									will provide faculty, staff, students, and
									scholars with the information they need to
									make good decisions about program
									participation and to facilitate their
									adjustment to the locales and cultures where
									they will study or work.
								</p>

								<h3 className="fls-post__title">Access</h3>

								<p className="fls__post-copy">
									In planning developing, and implementing our
									programs we will strive to ensure that they
									are accessible to all qualified individuals,
									doing our utmost to guarantee that
									international education is available to all
									who desire it and can benefit from it.
								</p>

								<h3 className="fls-post__title">
									Responsiveness
								</h3>

								<p className="fls__post-copy">
									We will maintain open and readily accessible
									communication with individuals in our
									programs and services and with our
									institutional partners. This includes
									providing students with the appropriate
									level of support based on age, experience,
									language ability, and placement.
								</p>
							</div>
						</div>
					</div>
				</div>
			</Section>

			<Section>
				<div className="columns is-multiline is-centered">
					<div className="column is-8 has-text-centered">
						<h3 className="subtitle subtitle--fls subtitle--red">
							About
						</h3>
						<h2 className="title title--fls">
							Accreditations & Affiliations
						</h2>

						<p className="fls__post-copy">
							FLS is one of a select number of schools accredited
							both by CEA (Commission on English Language Program
							Accreditation) and ACCET (Accrediting Council on
							Continuing Education and Training). Both are
							national accrediting agencies recognized by the U.S.
							Department of Education. We are also members of the
							American Association of Intensive English Programs
							(AAIEP) and active participants in NAFSA and TESOL.
						</p>
					</div>

					<div className="column is-full">
						<div className="columns is-multiline">
							{/* TODO: Should come from the CMS */}
							<Card isAffiliate={true} />
						</div>
					</div>
				</div>
			</Section>

			<Section sectionClasses={['section']}>
				<div className="columns is-centered is-multiline">
					<div className="column is-8 has-text-centered">
						<h3 className="subtitle subtitle--fls subtitle--red">
							Meet the Team
						</h3>
						<h2 className="title title--fls">Contact FLS</h2>

						<p className="fls__post-copy">
							Call or email us with any questions about FLS
							international or this website.
						</p>
					</div>
				</div>

				<div className="columns is-multiline">
					<div className="column is-full">
						<h3 className="fls-post__title">
							FLS International Administrators
						</h3>
					</div>

					<Card isContact={true} />
				</div>
			</Section>
		</Fragment>
	);
};

const AboutUsPage = ({ data }) => {
	// const { frontmatter } = data.markdownRemark;

	return (
		<Layout isScrolled={true} hasNavHero={true} pageTitle={'About Us'}>
			<AboutUsTemplate />
		</Layout>
	);
};

export default AboutUsPage;

// TODO: Here, all the individual fields are specified.
// Is there a way to just say 'get all fields'?
// export const pageQuery = graphql`
// 	query {
// 		markdownRemark {
// 			frontmatter {
// 				program_cards {
// 					card_description
// 					card_image
// 					card_title
// 				}
// 			}
// 		}
// 	}
// `;
