import React from 'react';

import Layout from 'src/components/Layout';
import Section from 'src/components/section/Section';
import HorizontalNav from 'src/components/horizontal-nav/HorizontalNav';
import MediaItem from 'src/components/media-item/MediaItem';

import 'src/styles/contact-us.scss';

export const DownloadsTemplate = () => {
	// TODO: This is a critical page that needs to be generated by the CMS. It should be possible to dynamically generate pages like this entirely through the CMS
	return (
		<Section>
			<div className="columns is-multiline">
				<div className="column is-full">
					{/* TODO: Needs to be made compatible for use on multiple pages */}
					<HorizontalNav
						navItems={[
							'Brochures',
							'Flyers',
							'Forms',
							'English Everywhere',
							'CA Accreditation Documentation',
						]}
						isDownloads={true}
					/>
				</div>

				<div className="column is-full">
					<div className="columns">
						<div className="column is-one-quarter">
							<MediaItem />
						</div>
					</div>
				</div>
			</div>
		</Section>
	);
};

const DownloadsPage = ({ data }) => {
	// const { frontmatter } = data.markdownRemark;

	return (
		<Layout isScrolled={true} hasNavHero={true} pageTitle={'Contact Us'}>
			<DownloadsTemplate />
		</Layout>
	);
};

export default DownloadsPage;

// TODO: Here, all the individual fields are specified.
// Is there a way to just say 'get all fields'?
// export const pageQuery = graphql`
// 	query {
// 		markdownRemark {
// 			frontmatter {
// 				program_cards {
// 					card_description
// 					card_image
// 					card_title
// 				}
// 			}
// 		}
// 	}
// `;
